name: CI Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  secret-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sast:
    name: SAST Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
       
      - name: Bandit (Python)
        run: |
            pip install bandit
            bandit -r user-service/app notification-service/app -ll -f json -o bandit-report.json || true
    
      - name: Upload Bnadit results
        uses: actions/upload-artifact@v4
        with:
            name: bandit-report
            path: bandit-report.json

